# define c++ compiler options and preprocessor definitions for all OS types
set(ICE_COMPILE_DEFS "ICE_BUILDING_SRC")
set(ICE_CPP11_COMPILE_DEFS "${ICE_COMPILE_DEFS}" "ICE_CPP11_MAPPING")
set(STATIC_ICE_COMPILE_DEFS "${ICE_COMPILE_DEFS}" "ICE_STATIC_LIBS")

if(NOT BUILD_SHARED_LIBS)
	set(ICE_COMPILE_DEFS "${STATIC_ICE_COMPILE_DEFS}")
endif()

list(APPEND COMPILE_SLICES_CPP_PARAMETERS "--include-dir")

if(MSVC)
	string(REGEX REPLACE "/INCREMENTAL *" "/INCREMENTAL:NO " 
		CMAKE_EXE_LINKER_FLAGS_DEBUG ${CMAKE_EXE_LINKER_FLAGS_DEBUG}
	)

	string(REGEX REPLACE "/INCREMENTAL *" "/INCREMENTAL:NO " 
		CMAKE_SHARED_LINKER_FLAGS_DEBUG ${CMAKE_SHARED_LINKER_FLAGS_DEBUG}
	
	)

	set(ICE_MSVC_COMPILE_DEFS
		"_CONSOLE" 
		"WIN32_LEAN_AND_MEAN" 
	)

	set(ICE_MSVC_COMPILE_OPTIONS
		"/W4"
		"/wd4121"
		"/wd4250"
		"/wd4251"
		"/wd4275"
		"/wd4324"
		"/wd4127"
		"/wd4505"
		"/wd4512"
		"/wd4834"
		"/MP"
		"/bigobj"
	)

	set(ICE_MSVC_LINK_OPTIONS
		"wsetargv.obj"
		"/OPT:NOLBR"
	)
	
	set(ICE_UWP_COMPILE_DEFS
		"WINAPI_FAMILY=2"
		"_UNICODE"
		"UNICODE"
	)

	set(ICE_UWP_COMPILE_OPTIONS
		"/wd4264"
		"/wd4221"
	)	
elseif(APPLE)
	# TODO - add ICE_COMPILE_DEFS
elseif(UNIX OR LINUX)
	# TODO - ICE_COMPILE_DEFS
endif()
