if(CMAKE_CXX_FLAGS MATCHES "/W[0-4]")
	string(REGEX REPLACE "/W[0-4]" "/W4" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
endif()

string(REGEX REPLACE "/INCREMENTAL *" "/INCREMENTAL:NO " 
	CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG}"
)

string(REGEX REPLACE "/INCREMENTAL *" "/INCREMENTAL:NO " 
	CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG}"
)

string(REGEX REPLACE "/OPT:LBR *" "/OPT:NOLBR " 
	CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG}"
)

string(REGEX REPLACE "/OPT:LBR *" "/OPT:NOLBR " 
	CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG}"
)

if(WIN32)
	set(ICE_COMPILE_DEFS
		${ICE_COMPILE_DEFS}
		"_CONSOLE" 
		"WIN32_LEAN_AND_MEAN"
		"_SBCS"
		"_WIN32_WINNT=0x603"
	)
elseif(WINDOWS_STORE)
	set(ICE_COMPILE_DEFS
		${ICE_COMPILE_DEFS}
		"WINAPI_FAMILY_PC_APP"
		"WIN32_LEAN_AND_MEAN"
	)
endif()

set(ICE_MSVC_COMPILE_OPTIONS
	"/wd4121"
	"/wd4250"
	"/wd4251"
	"/wd4275"
	"/wd4324"
	"/wd4127"
	"/wd4505"
	"/wd4512"
	"/wd4834"
	"/MP"
	"/bigobj"
)

if(BUILD_ICE_UWP)
	set(ICE_MSVC_COMPILE_OPTIONS
		${ICE_MSVC_COMPILE_OPTIONS}
		"/wd4264"
		"/wd4221"
		"/ZW"
	)
endif()

set(ICE_MSVC_APP_LINK_OPTIONS
	"wsetargv.obj"
)

set(ICE_MSVC_DLL_LINK_OPTIONS
	"/ERRORREPORT:QUEUE 
	/NOLOGO 
	/MANIFEST 
	/MANIFESTUAC:\"level='asInvoker' uiAccess='false'\" 
	/NXCOMPAT 
	/DYNAMICBASE 
	/TLBID:1"
)

if(BUILD_ICE_UWP)
	set(ICE_MSVC_DLL_LINK_OPTIONS
		"${ICE_MSVC_DLL_LINK_OPTIONS} /WHOLEARCHIVE"
	)
endif()
